images: docker

services:
  - docker: dind

stages:
  - test
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

Test:
  stage: test
  script:
    - echo "Tests passed!"

Deploy:
  stage: test
  script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - docker-compose up -d --build
  environment: 
    - name: production
      url: http://34.132.72.31
