stages:
  - test

Test:
  image: docker:latest
  stage: test
  script:
    - cd customer && docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    - echo "Test Passed for new Runner!"
